### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by sajadmartiny** [FireZenk/AudioWaves#1]
when build sample  on my phone (api17) , return null for dispatcher in prepare and crashed sample,

01-05 16:32:57.105 32068-32068/org.firezenk.audiowaves.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{org.firezenk.audiowaves.sample/org.firezenk.audiowaves.sample.MainActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class org.firezenk.audiowaves.Visualizer
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:165)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5391)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                                 Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class org.firezenk.audiowaves.Visualizer
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
                                                                                    at org.firezenk.audiowaves.sample.MainActivity.onCreate(MainActivity.java:15)
                                                                                    at android.app.Activity.performCreate(Activity.java:5122)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:165) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5391) 
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                                    at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249) 
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                                    at org.firezenk.audiowaves.sample.MainActivity.onCreate(MainActivity.java:15) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5122) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:165) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5391) 
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                                 Caused by: java.lang.NullPointerException
                                                                                    at org.firezenk.audiowaves.Visualizer.prepare(Visualizer.java:290)
                                                                                    at org.firezenk.audiowaves.Visualizer.init(Visualizer.java:152)
                                                                                    at org.firezenk.audiowaves.Visualizer.<init>(Visualizer.java:71)
                                                                                    at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249) 
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                                    at org.firezenk.audiowaves.sample.MainActivity.onCreate(MainActivity.java:15) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5122) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:165) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5391) 
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by msoner1** [comment]
You need to give permission to access the microphone.If you did it in AndroidManifest.Check your phone settings in Settings/Apps/[Your_app]/Permissions/... and you enabled Microphone.
